import { DEMO_IDS } from "@/shared/demo-constants";
import type { Resident } from "@/shared/types";
import { syntheticResidents } from "@/features/resident/synthetic-residents";

const baseResidents = [
  {
    id: DEMO_IDS.residents.zhangNainai,
    name: "张奶奶",
    age: 82,
    hukou: "北京市",
    livingStatus: "独居",
    lowIncomeStatus: "低保",
    disabilityStatus: "是否完成失能评估未知",
    insuranceStatus: "参保状态待核实",
    labels: ["高龄", "独居", "低保", "失能待核实"],
  },
  {
    id: DEMO_IDS.residents.liShu,
    name: "李叔",
    age: 68,
    hukou: "北京市",
    livingStatus: "与家人同住",
    lowIncomeStatus: "非低保",
    disabilityStatus: "无残疾登记",
    insuranceStatus: "已参加城乡居民医疗保险",
    labels: ["本地户籍", "与家人同住", "医保已确认"],
  },
  {
    id: DEMO_IDS.residents.wangNainai,
    name: "王奶奶",
    age: 84,
    hukou: "户籍信息待核实",
    livingStatus: "独居",
    lowIncomeStatus: "收入情况待核实",
    disabilityStatus: "疑似行动不便，评估结果待核实",
    insuranceStatus: "参保状态待核实",
    labels: ["高龄", "独居", "户籍待核实", "收入待核实"],
  },
  {
    id: "resident-004",
    name: "赵阿姨",
    age: 76,
    hukou: "北京市",
    livingStatus: "与配偶同住",
    lowIncomeStatus: "低收入家庭",
    disabilityStatus: "无残疾登记",
    insuranceStatus: "已参加城乡居民养老保险",
    labels: ["低收入", "养老保险", "本地户籍"],
  },
  {
    id: "resident-005",
    name: "陈大爷",
    age: 91,
    hukou: "北京市",
    livingStatus: "与子女同住",
    lowIncomeStatus: "经济状况待核实",
    disabilityStatus: "持残疾证，等级待核实",
    insuranceStatus: "参保状态正常",
    labels: ["高龄", "残疾等级待核实", "材料待补充"],
  },
  {
    id: "resident-006",
    name: "孙阿姨",
    age: 63,
    hukou: "北京市",
    livingStatus: "独居",
    lowIncomeStatus: "收入证明待补充",
    disabilityStatus: "无残疾登记",
    insuranceStatus: "已参加城乡居民医疗保险",
    labels: ["独居", "收入待核实", "走访关注"],
  },
  {
    id: "resident-007",
    name: "周奶奶",
    age: 87,
    hukou: "北京市",
    livingStatus: "与子女同住",
    lowIncomeStatus: "非低保",
    disabilityStatus: "轻度失能",
    insuranceStatus: "参保状态正常",
    labels: ["高龄", "轻度失能", "本地户籍"],
  },
  {
    id: "resident-008",
    name: "吴师傅",
    age: 58,
    hukou: "外省户籍",
    livingStatus: "租住",
    lowIncomeStatus: "非低保",
    disabilityStatus: "无残疾登记",
    insuranceStatus: "异地参保信息待核实",
    labels: ["人户分离", "异地参保", "信息待完善"],
  },
] satisfies Resident[];

export const mockResidents = [...baseResidents, ...syntheticResidents];
